### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [AeroNotix/ryeboy#1]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by AeroNotix** [comment]
I'd forgotten that Ryeboy got accepted into QuickLisp. I'll get around to this when I get a sec, PRs also welcome.

**Comment by AeroNotix** [comment]
@hydandata I think was done at some point since 2015.
