### ISSUE TITLE
Does not build - missing package

### ISSUE THREAD

**Issue by quicklisp** [AeroNotix/ryeboy#3]
I get this: `READ error during COMPILE-FILE: Package COM.APHYR.RIEMANN does not exist`

Log here: http://report.quicklisp.org/2020-06-05/failure-report/ryeboy.html#ryeboy

**Comment by AeroNotix** [comment]
@quicklisp What are you running when you run these tests?

**Comment by quicklisp** [comment]
`(asdf:load-system "ryeboy")`

**Comment by AeroNotix** [comment]
Please try with the master branch/commit.

**Comment by quicklisp** [comment]
Now I get this: `Package IO.RIEMANNG.RIEMANN does not exist.`

**Comment by AeroNotix** [comment]
Sorry, typo, fixed now.

**Comment by quicklisp** [comment]
Great, it builds fine for me now.
